### ISSUE TITLE
größere default_max_prefixlen in mkroa

### ISSUE THREAD

**Issue by ka-ba** [freifunk/icvpn-scripts#29]
Derzeit ist default_max_prefixlen in mkroa 0; sowohl für IPv4, als auch für IPv6. Vermutlich setzen viele communities, die mkroa überhaupt nutzen, das tool mit default-Einstellungen ein.

Es ist im ICVPN gängige Praxis (gerade für v6, aber auch für v4), das gesamte zugewiesene Netz im icvpn-meta anzugeben. Bei v4 ist das gewöhnlich /16, bei v6 oft /48. Auf der anderen Seite nutzen viele communities (vorerst) aber nur eines, oder einige Subnetze davon (z.B. /18, bzw. /64). Nur die genutzten Subnetze werden per BGP announce-t.
Diese Praxis ist IMHO auch nicht zu beanstanden. Sie erlaubt viel Flexibilität ohne ständige Änderungen im icvpn-meta. In meinen Augen ist die Nutzung genau so gedacht.

Wird mkroa mit default-Einstellungen betrieben, so werden alle diese beschriebenen Subnetze im BGP abgelehnt und nicht ins routing genommen.

Deshalb Vorschlag: der default-Wert für max_prefixlen in mkroa sollte IP-versionsabhängig /20 bzw. /64 betragen.

**Comment by tcatm** [comment]
Ich habe gerade einen Commit gepusht, der die defaults auf /24, /64 setzt. Das sollte das Problem mit Ausnahme für die Hostrouten aus einigen OLSR Netzen lösen.
