### ISSUE TITLE
add a licence

### ISSUE THREAD

**Issue by booo** [freifunk/icvpn-scripts#9]
We should add a licence (file) to this repository.

**Comment by jplitza** [comment]
Valid point, everything should have a license. I suggest and usually use [MIT](http://opensource.org/licenses/MIT) as it is as liberal as it gets and has no strings attached. I could also settle with [BSD 3-clause](http://opensource.org/licenses/BSD-3-Clause) or [BSD 2-clause](http://opensource.org/licenses/BSD-2-Clause). GPL is far too blown up for this small stuff.

As far as I can see, these other people have up to now contributed to this repository:
* @tcatm 
* @thomasDOTde 
* @kpcyrd (splitting off the formatter, 804eb16e147f269c712d535d8d1aa7c3b02e5e93)

Could all of them please leave a short notice here, with which of the above-mentioned licenses they agree, or suggest alternatives if absolutely necessary.

**Comment by thomasDOTde** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I'm fine with all of them.

On 12.01.2015 19:03, Jan-Philipp Litza wrote:
>
> Valid point, everything should have a license. I suggest and usually
use MIT <http://opensource.org/licenses/MIT> as it is as liberal as it
gets and has no strings attached. I could also settle with BSD 3-clause
<http://opensource.org/licenses/BSD-3-Clause> or BSD 2-clause
<http://opensource.org/licenses/BSD-2-Clause>. GPL is far too blown up
for this small stuff.
>
> As far as I can see, these other people have up to now contributed to
this repository:
>
>   * @tcatm <https://github.com/tcatm>
>   * @thomasDOTde <https://github.com/thomasDOTde>
>   * @kpcyrd <https://github.com/kpcyrd> (splitting off the formatter,
804eb16
<https://github.com/freifunk/icvpn-scripts/commit/804eb16e147f269c712d535d8d1aa7c3b02e5e93>)
>
> Could all of them please leave a short notice here, with which of the
above-mentioned licenses they agree, or suggest alternatives if
absolutely necessary.
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/freifunk/icvpn-scripts/issues/9#issuecomment-69614721>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJUtA2UAAoJED0ncubs34cjeQkIAKjGy6k/so3GXACfZ1m/tond
3P1O5a8GsccDu5nFHEzgJC/diXSLc/DTXRTY7izSFZHpIgURoEYQRHqvnBzavvjo
u224T3COkIWcoVKFKzz3bQ+s9lKhPAHjugPLiUFn76GJMrrBY3OZDNo8ZlOsLFYz
4v4coR5G1Q06tYekRgyl0jAeezB3qMuK1jahWPMrXLuH2LEYCnjl6IQBw1ddhzZl
Y8JIQLK8ZSiAChvCZuwBa5nmB3BAwySK+VukLkm6NlSY+9gRDgonQlt7iDYzttVj
9XUJ+k2J4gwPTX6vSHjDFrTucb07guU8VcSJ7FZP8Sy54Zs/F+Ik6nEnxXUUuqY=
=mOOg
-----END PGP SIGNATURE-----

**Comment by tcatm** [comment]
I'm fine with any of the mentioned licenses, too.

**Comment by kpcyrd** [comment]
I'm ok with any of the mentioned licenses.

**Comment by jplitza** [comment]
I added MIT and struggled a bit with the "copyright holders" placeholder. I ended up entering Nils and myself by name, and added "and others" at the end for two reasons:
* the git log doesn't state realnames for @kpcyrd and @thomasDOTde, and I wasn't sure if they should be mentioned
* Nils and I have contributed the most [[1]](https://github.com/freifunk/icvpn-scripts/graphs/contributors)
If anybody is not okay with that, please file a pull request with fixes, this is just a suggestion.

**Comment by booo** [comment]
Some project keep a AUTHORS file for this reason, e.g. the django project: https://github.com/django/django/blob/master/AUTHORS
